# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libnetcdf-dev 
      - netcdf-bin

after_success:
  - Rscript -e 'covr::codecov()'
  