# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages


after_success:
  - Rscript -e 'covr::codecov()'

r_binary_packages:
  - ncdf4